---
# Configure the internal domain name of the cluster here.
cluster_base_domain: "redhat.com"
cluster_domain_name: "{{ cluster_name }}.{{ cluster_base_domain }}"
cluster_name: crw-ocp-latest

# The URL of of the archive containing the
# RHCOS kernel, initramfs, and disk images
rhcos_version: "4.6.1"
rhcos_download_url: "https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.6/4.6.1/"

# The download URL of the openshift-install binary
openshift_install_binary_url: "https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/4.6.1/openshift-install-linux.tar.gz"

# The public DNS server to use.  This should be
# changed to a DNS server on your intranet.
dns_nameserver: 10.11.5.19

# The IP address of the local network
# gateway, and the netmask/cidr of
# the subnet
subnet_gateway: 10.0.158.0
subnet_netmask: 255.255.255.0
subnet_cidr: 10.0.158.0/24
subnet_in_addr_name: "{{ subnet_cidr.split('.')[:3] | reverse | join('.') }}"

# This is the IP address of the bastion which the
# cluster nodes can see.
bastion_private_ip_address: 10.0.158.57
# This is the IP address of the bastion
# when the bastion is configures as a dhcp
# server.  Otherwise it is ignored.
dhcp_server_ip_address: 10.0.158.57

# z/VM kernel parameters
# User must supply zvm rd.znet device id
# based on their own environment.
# example:
# "rd.znet=qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portno=0"
zvm_rd_znet: "rd.znet=qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portno=0 zfcp.allow_lun_scan=0"
# User must supply zvm rd.dasd device id kernel arg.
# This is the device to install coreos to.
# WARNING - using the wrong device id could result in loss of data.  The
# device used in this example is not necessarily correct for your
# environment.
# example:
# "rd.dasd=0.0.0120"
zvm_rd_dasd: "rd.dasd=0.0.0120,0.0.0130-0.0.013F"

coreos_kargs_net:
  zvm: "ip={{ cluster_nodes[coreos_role][item].ip }}::{{ subnet_gateway }}:{{ subnet_netmask }}:::none nameserver={{ bastion_private_ip_address }} {{ zvm_rd_znet }}"

coreos_kargs_extra:
  zvm:  "{{ zvm_rd_dasd }}"

dev_disk:
  zvm: dasda

# This is the default node configuration.
# Please ensure the MAC addresses are
# correct for the hardware you are deploying to.
# The IP addresses must be on the same subnet as
# the {{ cluster_subnet_prefix }}
# CHANGEME!
cluster_nodes:
  bootstrap:
    bootstrap-0:
      mac: '52:54:00:d0:f7:03'
      ip: '10.0.158.74'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: bootstrap.ign
  masters:
    master-0:
      mac: '52:54:00:da:70:41'
      ip: '10.0.158.58'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: master.ign
    master-1:
      mac: '52:54:00:a2:93:d8'
      ip: '10.0.158.59'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: master.ign
    master-2:
      mac: '52:54:00:d9:5b:d8'
      ip: '10.0.158.60'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: master.ign
  workers:
    infra-0:
      mac: '52:54:00:70:8b:74'
      ip: '10.0.158.71'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    infra-1:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.72'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    infra-2:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.73'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-0:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.61'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-1:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.62'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-2:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.63'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-3:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.64'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-4:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.65'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-5:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.66'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-6:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.67'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-7:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.68'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-8:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.69'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign
    worker-9:
      mac: '52:54:00:70:8b:75'
      ip: '10.0.158.70'
      disk: "{{ dev_disk[install_mode] }}"
      ign_profile: worker.ign

# The following variables should generally not need to be edited

install_mode: zvm

# This will be the same as the bastion private ip when
# bastion is a separate VM, otherwise it is the gateway ip.
# dhcp_server_ip_address is not used by default in a z/VM install
bastion_public_ip_address: "{{ ansible_default_ipv4.address }}"

# pxe_mode (grub, pxelinux)
# use pxelinux mode for zvm to generate
# parmfiles, then punch and IPL manually
pxe_mode: pxelinux

ocp4_pull_secret: "{{ lookup('file', '~/.ocp4_pull_secret') | from_json }}"

rhcos_disk_type:
  zvm: dasd  # or metal

rhcos_installer_initramfs: 'rhcos-{{ rhcos_version }}-s390x-live-initramfs.s390x.img'
rhcos_installer_kernel: 'rhcos-{{ rhcos_version }}-s390x-live-kernel-s390x'
rhcos_disk_image: 'rhcos-{{ rhcos_version }}-s390x-{{ rhcos_disk_type[install_mode] }}.s390x.raw.gz'

rhcos_download_files:
  - '{{ rhcos_installer_initramfs }}'
  - '{{ rhcos_installer_kernel }}'
